services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"  # Mapeia a porta do container para a máquina host
    volumes:
      - .:/app  # Para que as alterações no código sejam refletidas automaticamente
    environment:
      - PYTHONUNBUFFERED=1  # Para não bufferizar os logs
      - MONGO_URI=mongodb://mongodb:27017/chat_app
    depends_on:
      - mongodb
    networks:
      - rede_interna

  mongodb:
    container_name: mongodb
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - rede_interna

volumes:
  mongodb_data:

networks:
  rede_interna:
    driver: bridge